import type { Establishment } from "../types";

export const establishments: Establishment[] = [
  {
    id: "rabat-central-hospital",
    name: "Rabat Central Hospital",
    category: "Hospital",
    address: "Avenue Al Maarif, Rabat",
    city: "Rabat",
    coordinates: { latitude: 33.9902, longitude: -6.8436 },
    status: "priority",
    reviews: 128,
    complaints: 9,
    recentSignal: "2 complaints this week",
    overallScore: 3,
    scoreCategories: { bribery: 2, hygiene: 3, waitTime: 1, equipment: 4, staff: 5 },
  },
  {
    id: "rabat-grand-poste",
    name: "La Grande Poste",
    category: "Public Office",
    address: "Avenue Mohammed V, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0195, longitude: -6.8362 },
    status: "verified",
    reviews: 72,
    complaints: 1,
    recentSignal: "Efficient mail processing",
    overallScore: 8,
    scoreCategories: { bribery: 9, hygiene: 8, waitTime: 6, equipment: 8, staff: 9 },
  },
  {
    id: "rabat-parlement",
    name: "Le Parlement du Maroc",
    category: "Public Office",
    address: "Avenue Mohammed V, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0182, longitude: -6.8368 },
    status: "priority",
    reviews: 154,
    complaints: 8,
    recentSignal: "High security checkpoint delays",
    overallScore: 4,
    scoreCategories: { bribery: 5, hygiene: 4, waitTime: 2, equipment: 5, staff: 4 },
  },
  {
    id: "hotel-balima",
    name: "Balima Minaret Suites",
    category: "Hotel",
    address: "Avenue Mohammed V, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0186, longitude: -6.8372 },
    status: "verified",
    reviews: 90,
    complaints: 0,
    recentSignal: "Renovated historical suites",
    overallScore: 9,
    scoreCategories: { bribery: 10, hygiene: 9, waitTime: 8, equipment: 9, staff: 9 },
  },
  {
    id: "mcdonalds-rabat-ville",
    name: "McDonald's Rabat Ville",
    category: "Restaurant",
    address: "Avenue Mohammed V, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0171, longitude: -6.8365 },
    status: "verified",
    reviews: 210,
    complaints: 3,
    recentSignal: "Busy during lunch hours",
    overallScore: 8,
    scoreCategories: { bribery: 10, hygiene: 8, waitTime: 7, equipment: 9, staff: 8 },
  },
  {
    id: "le-petit-beur",
    name: "Le Petit Beur",
    category: "Restaurant",
    address: "Rue Damas, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0180, longitude: -6.8350 },
    status: "verified",
    reviews: 88,
    complaints: 2,
    recentSignal: "Authentic tagine and couscous",
    overallScore: 7,
    scoreCategories: { bribery: 9, hygiene: 7, waitTime: 6, equipment: 7, staff: 8 },
  },
  {
    id: "boho-cafe",
    name: "Boho Cafe",
    category: "Cafe",
    address: "Rue Moulay Rachid, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0205, longitude: -6.8395 },
    status: "new",
    reviews: 12,
    complaints: 0,
    recentSignal: "Excellent specialty coffee",
    overallScore: 6,
    scoreCategories: { bribery: 8, hygiene: 7, waitTime: 5, equipment: 6, staff: 6 },
  },
  {
    id: "cozy-cafe",
    name: "Cozy Cafe",
    category: "Cafe",
    address: "Avenue Allal Ben Abdallah, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0165, longitude: -6.8340 },
    status: "watch",
    reviews: 43,
    complaints: 4,
    recentSignal: "WiFi instability reported",
    overallScore: 5,
    scoreCategories: { bribery: 7, hygiene: 5, waitTime: 4, equipment: 3, staff: 6 },
  },
  {
    id: "rabat-medina-market",
    name: "Bab El Had Medina Market",
    category: "Marketplace",
    address: "Avenue Hassan II, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0215, longitude: -6.8405 },
    status: "priority",
    reviews: 320,
    complaints: 18,
    recentSignal: "Congested walkways, watch for pickpockets",
    overallScore: 3,
    scoreCategories: { bribery: 4, hygiene: 2, waitTime: 3, equipment: 2, staff: 3 },
  },
  {
    id: "clinic-des-orangers",
    name: "Clinique des Orangers",
    category: "Clinic",
    address: "Rue d'Orangers, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0135, longitude: -6.8445 },
    status: "watch",
    reviews: 55,
    complaints: 6,
    recentSignal: "Long wait times at reception",
    overallScore: 4,
    scoreCategories: { bribery: 6, hygiene: 5, waitTime: 3, equipment: 5, staff: 4 },
  },
  {
    id: "lycee-descartes",
    name: "Lycée Descartes",
    category: "School",
    address: "Avenue Chellah, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0112, longitude: -6.8392 },
    status: "verified",
    reviews: 145,
    complaints: 2,
    recentSignal: "Strong academic rating",
    overallScore: 9,
    scoreCategories: { bribery: 10, hygiene: 9, waitTime: 8, equipment: 9, staff: 9 },
  },
  {
    id: "dar-naji",
    name: "Dar Naji Restaurant",
    category: "Restaurant",
    address: "Avenue Al Jazair, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0150, longitude: -6.8410 },
    status: "verified",
    reviews: 198,
    complaints: 5,
    recentSignal: "Popular traditional Moroccan dining",
    overallScore: 8,
    scoreCategories: { bribery: 9, hygiene: 8, waitTime: 7, equipment: 8, staff: 9 },
  },
  {
    id: "villa-mandarine",
    name: "Villa Mandarine",
    category: "Hotel",
    address: "Rue Ouled Bousbaa, Rabat",
    city: "Rabat",
    coordinates: { latitude: 33.9725, longitude: -6.8290 },
    status: "verified",
    reviews: 76,
    complaints: 1,
    recentSignal: "Tranquil orange grove gardens",
    overallScore: 9,
    scoreCategories: { bribery: 10, hygiene: 10, waitTime: 9, equipment: 9, staff: 9 },
  },
  {
    id: "mauresque-cafe",
    name: "Café Maure Kasbah",
    category: "Cafe",
    address: "Kasbah of the Udayas, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0322, longitude: -6.8315 },
    status: "verified",
    reviews: 112,
    complaints: 1,
    recentSignal: "Stunning river views, tea and pastries",
    overallScore: 8,
    scoreCategories: { bribery: 9, hygiene: 8, waitTime: 7, equipment: 8, staff: 8 },
  },
  {
    id: "national-library-rabat",
    name: "Bibliothèque Nationale",
    category: "Library",
    address: "Avenue Ibn Khaldoun, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0068, longitude: -6.8475 },
    status: "verified",
    reviews: 250,
    complaints: 3,
    recentSignal: "Excellent study environment and resources",
    overallScore: 8,
    scoreCategories: { bribery: 9, hygiene: 9, waitTime: 8, equipment: 8, staff: 8 },
  },
  {
    id: "rabat-art-museum",
    name: "Mohammed VI Art Museum",
    category: "Public Office",
    address: "Avenue Allal Ben Abdallah, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0155, longitude: -6.8360 },
    status: "verified",
    reviews: 84,
    complaints: 0,
    recentSignal: "Clean facilities and rich exhibits",
    overallScore: 9,
    scoreCategories: { bribery: 10, hygiene: 9, waitTime: 9, equipment: 9, staff: 8 },
  },
  {
    id: "cinema-renaissance",
    name: "Café Renaissance",
    category: "Cafe",
    address: "Avenue Mohammed V, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0177, longitude: -6.8369 },
    status: "verified",
    reviews: 49,
    complaints: 1,
    recentSignal: "Cultural hub for music and films",
    overallScore: 7,
    scoreCategories: { bribery: 9, hygiene: 7, waitTime: 7, equipment: 7, staff: 8 },
  },
  {
    id: "hasan-tower-plaza",
    name: "Hassan Tower Plaza",
    category: "Marketplace",
    address: "Boulevard Abi Regreg, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0240, longitude: -6.8225 },
    status: "priority",
    reviews: 412,
    complaints: 12,
    recentSignal: "High tourist traffic, access gates restricted",
    overallScore: 4,
    scoreCategories: { bribery: 5, hygiene: 4, waitTime: 3, equipment: 4, staff: 4 },
  },
  {
    id: "souk-el-sebbat",
    name: "Souk El Sebbat",
    category: "Marketplace",
    address: "Rue Souk Semmarine, Rabat Medina",
    city: "Rabat",
    coordinates: { latitude: 34.0268, longitude: -6.8365 },
    status: "new",
    reviews: 34,
    complaints: 2,
    recentSignal: "New pedestrian guides added",
    overallScore: 6,
    scoreCategories: { bribery: 7, hygiene: 5, waitTime: 6, equipment: 5, staff: 6 },
  },
  {
    id: "casablanca-tech-school",
    name: "Casablanca Tech School",
    category: "School",
    address: "Bourgogne District, Casablanca",
    city: "Casablanca",
    coordinates: { latitude: 33.5899, longitude: -7.6039 },
    status: "verified",
    reviews: 64,
    complaints: 2,
    recentSignal: "Top-rated by students",
    overallScore: 9,
    scoreCategories: { bribery: 9, hygiene: 9, waitTime: 8, equipment: 9, staff: 9 },
  },
  {
    id: "marrakesh-civic-office",
    name: "Marrakesh Civic Office",
    category: "Public Office",
    address: "Gueliz, Marrakesh",
    city: "Marrakesh",
    coordinates: { latitude: 31.6288, longitude: -7.9811 },
    status: "watch",
    reviews: 47,
    complaints: 5,
    recentSignal: "Queue delays reported",
    overallScore: 5,
    scoreCategories: { bribery: 6, hygiene: 5, waitTime: 3, equipment: 5, staff: 5 },
  },
  {
    id: "tangier-community-clinic",
    name: "Tangier Community Clinic",
    category: "Clinic",
    address: "Iberia Quarter, Tangier",
    city: "Tangier",
    coordinates: { latitude: 35.7595, longitude: -5.8340 },
    status: "new",
    reviews: 18,
    complaints: 1,
    recentSignal: "Recently added to the map",
    overallScore: 6,
    scoreCategories: { bribery: 7, hygiene: 6, waitTime: 5, equipment: 6, staff: 6 },
  },
  {
    id: "fez-central-library",
    name: "Fez Central Library",
    category: "Library",
    address: "Ville Nouvelle, Fez",
    city: "Fez",
    coordinates: { latitude: 34.0243, longitude: -5.0003 },
    status: "verified",
    reviews: 92,
    complaints: 0,
    recentSignal: "Clean record for 30 days",
    overallScore: 8,
    scoreCategories: { bribery: 10, hygiene: 8, waitTime: 8, equipment: 8, staff: 8 },
  },
  {
    id: "agadir-coastal-market",
    name: "Agadir Coastal Market",
    category: "Marketplace",
    address: "Corniche, Agadir",
    city: "Agadir",
    coordinates: { latitude: 30.4278, longitude: -9.5981 },
    status: "watch",
    reviews: 35,
    complaints: 4,
    recentSignal: "Access and pricing concerns",
    overallScore: 5,
    scoreCategories: { bribery: 4, hygiene: 5, waitTime: 4, equipment: 5, staff: 6 },
  },
  {
    id: "universite-mohammed-v-rabat",
    name: "Université Mohammed V",
    category: "University",
    address: "Avenue des Nations Unies, Agdal, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0042, longitude: -6.8550 },
    status: "verified",
    reviews: 245,
    complaints: 1,
    recentSignal: "Busy enrollment period",
    overallScore: 8,
    scoreCategories: { bribery: 9, hygiene: 8, waitTime: 6, equipment: 8, staff: 8 },
  },
  {
    id: "mosquee-hassan-ii-casablanca",
    name: "Mosquée Hassan II",
    category: "Mosque",
    address: "Boulevard de la Corniche, Casablanca",
    city: "Casablanca",
    coordinates: { latitude: 33.6085, longitude: -7.6326 },
    status: "new",
    reviews: 298,
    complaints: 0,
    recentSignal: "Beautiful morning views, high visitor count",
    overallScore: 7,
    scoreCategories: { bribery: 8, hygiene: 7, waitTime: 6, equipment: 7, staff: 7 },
  },
  {
    id: "gare-casa-voyageurs-casablanca",
    name: "Casablanca Voyageurs Station",
    category: "Train Station",
    address: "Boulevard Bahmad, Casablanca",
    city: "Casablanca",
    coordinates: { latitude: 33.5892, longitude: -7.5906 },
    status: "priority",
    reviews: 180,
    complaints: 11,
    recentSignal: "Ticket machine queues at peak hours",
    overallScore: 3,
    scoreCategories: { bribery: 5, hygiene: 3, waitTime: 2, equipment: 3, staff: 4 },
  },
  {
    id: "morocco-mall-casablanca",
    name: "Morocco Mall",
    category: "Market",
    address: "Boulevard de l'Océan Atlantique, Casablanca",
    city: "Casablanca",
    coordinates: { latitude: 33.5768, longitude: -7.7063 },
    status: "new",
    reviews: 220,
    complaints: 3,
    recentSignal: "Popular weekend shopping destination",
    overallScore: 7,
    scoreCategories: { bribery: 8, hygiene: 7, waitTime: 5, equipment: 7, staff: 7 },
  },
  {
    id: "attijariwafa-bank-casablanca",
    name: "Attijariwafa Bank Headquarters",
    category: "Bank",
    address: "Boulevard Moulay Youssef, Casablanca",
    city: "Casablanca",
    coordinates: { latitude: 33.5962, longitude: -7.6215 },
    status: "watch",
    reviews: 42,
    complaints: 7,
    recentSignal: "ATM out of service on Sunday",
    overallScore: 4,
    scoreCategories: { bribery: 6, hygiene: 5, waitTime: 4, equipment: 3, staff: 5 },
  },
  {
    id: "chu-ibn-rochd-casablanca",
    name: "CHU Ibn Rochd",
    category: "Hospital",
    address: "Rue des Hôpitaux, Casablanca",
    city: "Casablanca",
    coordinates: { latitude: 33.5775, longitude: -7.6234 },
    status: "priority",
    reviews: 115,
    complaints: 14,
    recentSignal: "High ER wait times reported",
    overallScore: 2,
    scoreCategories: { bribery: 3, hygiene: 2, waitTime: 1, equipment: 4, staff: 3 },
  },
  {
    id: "city-club-abdelmoumen-casablanca",
    name: "City Club Abdelmoumen",
    category: "Gym",
    address: "Boulevard Abdelmoumen, Casablanca",
    city: "Casablanca",
    coordinates: { latitude: 33.5790, longitude: -7.6180 },
    status: "watch",
    reviews: 95,
    complaints: 8,
    recentSignal: "Locker room maintenance requested",
    overallScore: 5,
    scoreCategories: { bribery: 7, hygiene: 4, waitTime: 5, equipment: 4, staff: 5 },
  },
  {
    id: "pharmacie-centrale-casablanca",
    name: "Pharmacie Centrale",
    category: "Pharmacy",
    address: "Avenue Mers Sultan, Casablanca",
    city: "Casablanca",
    coordinates: { latitude: 33.5855, longitude: -7.6130 },
    status: "new",
    reviews: 30,
    complaints: 1,
    recentSignal: "Well stocked with essential medicines",
    overallScore: 6,
    scoreCategories: { bribery: 8, hygiene: 6, waitTime: 6, equipment: 6, staff: 6 },
  },
  {
    id: "megarama-cinema-casablanca",
    name: "Megarama Cinema",
    category: "Cinema",
    address: "Boulevard de la Corniche, Ain Diab, Casablanca",
    city: "Casablanca",
    coordinates: { latitude: 33.6020, longitude: -7.6650 },
    status: "new",
    reviews: 145,
    complaints: 2,
    recentSignal: "New blockbuster releases drawing crowds",
    overallScore: 7,
    scoreCategories: { bribery: 8, hygiene: 7, waitTime: 6, equipment: 7, staff: 7 },
  },
  {
    id: "jardin-majorelle-marrakesh",
    name: "Jardin Majorelle",
    category: "Park",
    address: "Rue Yves Saint Laurent, Marrakesh",
    city: "Marrakesh",
    coordinates: { latitude: 31.6418, longitude: -8.0033 },
    status: "new",
    reviews: 280,
    complaints: 4,
    recentSignal: "Online booking required, long entry lines",
    overallScore: 6,
    scoreCategories: { bribery: 8, hygiene: 7, waitTime: 4, equipment: 7, staff: 6 },
  },
  {
    id: "cafe-des-epices-marrakesh",
    name: "Café des Épices",
    category: "Cafe",
    address: "Rahba Kedima, Medina, Marrakesh",
    city: "Marrakesh",
    coordinates: { latitude: 31.6280, longitude: -7.9865 },
    status: "new",
    reviews: 190,
    complaints: 1,
    recentSignal: "Excellent spice tea and rooftop views",
    overallScore: 7,
    scoreCategories: { bribery: 8, hygiene: 7, waitTime: 6, equipment: 7, staff: 7 },
  },
  {
    id: "gare-de-marrakech-marrakesh",
    name: "Gare de Marrakech",
    category: "Train Station",
    address: "Avenue Hassan II, Gueliz, Marrakesh",
    city: "Marrakesh",
    coordinates: { latitude: 31.6300, longitude: -8.0195 },
    status: "watch",
    reviews: 150,
    complaints: 5,
    recentSignal: "Taxi queue delays outside station",
    overallScore: 5,
    scoreCategories: { bribery: 6, hygiene: 5, waitTime: 3, equipment: 5, staff: 5 },
  },
  {
    id: "mosquee-koutoubia-marrakesh",
    name: "Koutoubia Mosque",
    category: "Mosque",
    address: "Medina, Marrakesh",
    city: "Marrakesh",
    coordinates: { latitude: 31.6238, longitude: -7.9936 },
    status: "new",
    reviews: 270,
    complaints: 0,
    recentSignal: "Iconic minaret landmark, clean plaza",
    overallScore: 7,
    scoreCategories: { bribery: 8, hygiene: 7, waitTime: 6, equipment: 7, staff: 7 },
  },
  {
    id: "la-mamounia-hotel-marrakesh",
    name: "La Mamounia",
    category: "Hotel",
    address: "Avenue Bab Jdid, Marrakesh",
    city: "Marrakesh",
    coordinates: { latitude: 31.6190, longitude: -7.9985 },
    status: "new",
    reviews: 210,
    complaints: 1,
    recentSignal: "World-class luxury gardens",
    overallScore: 7,
    scoreCategories: { bribery: 8, hygiene: 7, waitTime: 6, equipment: 8, staff: 7 },
  },
  {
    id: "universite-cadi-ayyad-marrakesh",
    name: "Université Cadi Ayyad",
    category: "University",
    address: "Boulevard Abdelkrim Al Khattabi, Marrakesh",
    city: "Marrakesh",
    coordinates: { latitude: 31.6475, longitude: -8.0140 },
    status: "priority",
    reviews: 130,
    complaints: 9,
    recentSignal: "Student registration congestion",
    overallScore: 4,
    scoreCategories: { bribery: 5, hygiene: 4, waitTime: 2, equipment: 5, staff: 4 },
  },
  {
    id: "universite-al-qarawiyyin-fez",
    name: "Université Al-Qarawiyyin",
    category: "University",
    address: "Medina, Fes",
    city: "Fes",
    coordinates: { latitude: 34.0647, longitude: -4.9736 },
    status: "new",
    reviews: 260,
    complaints: 0,
    recentSignal: "Historic library and courtyard",
    overallScore: 7,
    scoreCategories: { bribery: 8, hygiene: 7, waitTime: 6, equipment: 7, staff: 7 },
  },
  {
    id: "gare-de-fes-fes",
    name: "Gare de Fès",
    category: "Train Station",
    address: "Boulevard des Almohades, Fes",
    city: "Fes",
    coordinates: { latitude: 34.0320, longitude: -5.0080 },
    status: "watch",
    reviews: 88,
    complaints: 6,
    recentSignal: "Renovation works in progress",
    overallScore: 5,
    scoreCategories: { bribery: 6, hygiene: 5, waitTime: 4, equipment: 4, staff: 5 },
  },
  {
    id: "bab-boujloud-market-fes",
    name: "Bab Boujloud Market",
    category: "Market",
    address: "Place Bab Boujloud, Medina, Fes",
    city: "Fes",
    coordinates: { latitude: 34.0615, longitude: -4.9825 },
    status: "priority",
    reviews: 175,
    complaints: 10,
    recentSignal: "Very crowded corridors, watch for tourists",
    overallScore: 3,
    scoreCategories: { bribery: 4, hygiene: 3, waitTime: 2, equipment: 3, staff: 4 },
  },
  {
    id: "gare-tanger-ville-tangier",
    name: "Tangier Ville Railway Station",
    category: "Train Station",
    address: "Boulevard Mohamed V, Tangier",
    city: "Tangier",
    coordinates: { latitude: 35.7725, longitude: -5.7980 },
    status: "new",
    reviews: 165,
    complaints: 3,
    recentSignal: "High-speed Al Boraq arrivals running on time",
    overallScore: 7,
    scoreCategories: { bribery: 8, hygiene: 7, waitTime: 6, equipment: 7, staff: 7 },
  },
  {
    id: "cafe-hafa-tangier",
    name: "Café Hafa",
    category: "Cafe",
    address: "Rue Hafa, Tangier",
    city: "Tangier",
    coordinates: { latitude: 35.7912, longitude: -5.8218 },
    status: "new",
    reviews: 205,
    complaints: 2,
    recentSignal: "Stunning views of the Strait of Gibraltar",
    overallScore: 7,
    scoreCategories: { bribery: 8, hygiene: 7, waitTime: 6, equipment: 7, staff: 7 },
  },
  {
    id: "port-tanger-ville-tangier",
    name: "Port de Tanger Ville",
    category: "Public Office",
    address: "Avenue d'Espagne, Tangier",
    city: "Tangier",
    coordinates: { latitude: 35.7865, longitude: -5.8080 },
    status: "priority",
    reviews: 140,
    complaints: 12,
    recentSignal: "Customs check queue times increased",
    overallScore: 3,
    scoreCategories: { bribery: 4, hygiene: 4, waitTime: 2, equipment: 3, staff: 3 },
  },
  {
    id: "souk-el-had-market-agadir",
    name: "Souk El Had",
    category: "Market",
    address: "Rue 2 Mars, Agadir",
    city: "Agadir",
    coordinates: { latitude: 30.4120, longitude: -9.5815 },
    status: "watch",
    reviews: 290,
    complaints: 8,
    recentSignal: "Massive market layout, parking challenges",
    overallScore: 5,
    scoreCategories: { bribery: 6, hygiene: 5, waitTime: 4, equipment: 5, staff: 5 },
  },
  {
    id: "aeroport-al-massira-agadir",
    name: "Airport Al Massira",
    category: "Airport",
    address: "Hachach, Agadir",
    city: "Agadir",
    coordinates: { latitude: 30.3250, longitude: -9.4120 },
    status: "new",
    reviews: 110,
    complaints: 4,
    recentSignal: "Smooth check-in, passenger queues normal",
    overallScore: 6,
    scoreCategories: { bribery: 8, hygiene: 6, waitTime: 5, equipment: 6, staff: 6 },
  },
];

export const statusStyles: Record<Establishment["status"], string> = {
  verified: "bg-emerald-100 text-emerald-700",
  watch: "bg-amber-100 text-amber-800",
  new: "bg-sky-100 text-sky-700",
  priority: "bg-rose-100 text-rose-700",
};

export const statusLabels: Record<Establishment["status"], string> = {
  verified: "Verified",
  watch: "Watchlist",
  new: "New",
  priority: "Priority",
};

export const mapCenter = {
  latitude: 34.02202576348649,
  longitude: -6.837746710969857,
};

export const mapCamera = {
  coordinates: mapCenter,
  zoom: 6.5,
};

export const mapProperties = {
  selectionEnabled: false,
};

export const categoryColors: Record<string, string> = {
  Hospital: "red",
  School: "#4CAF50",
  Marketplace: "green",
  Market: "green",
  "Public Office": "purple",
  Clinic: "orange",
  Library: "teal",
  Restaurant: "orange",
  Cafe: "teal",
  Hotel: "blue",
  University: "#2196F3",
  Government: "#9C27B0",
  Shop: "#FF9800",
  Pharmacy: "#00BCD4",
  Bank: "#607D8B",
  Gym: "#F44336",
  Cinema: "#E91E63",
  Park: "#8BC34A",
  Mosque: "#795548",
  "Train Station": "#3F51B5",
  "Bus Station": "#009688",
  Airport: "#03A9F4",
  "Post Office": "#FF5722",
};

export const markers = establishments.map((item) => ({
  id: item.id,
  coordinates: item.coordinates,
  showCallout: false,
  zIndex: item.status === "priority" ? 10 : 1,
  tintColor:
    item.overallScore !== undefined && item.overallScore >= 7
      ? "#22C55E"
      : item.overallScore !== undefined && item.overallScore >= 4
        ? "#EAB308"
        : "#EF4444",
}));
