import type { Establishment } from "../types";

export const establishments: Establishment[] = [
  {
    id: "rabat-central-hospital",
    name: "Rabat Central Hospital",
    category: "Hospital",
    address: "Avenue Al Maarif, Rabat",
    city: "Rabat",
    coordinates: { latitude: 33.9902, longitude: -6.8436 },
    status: "priority",
    reviews: 128,
    complaints: 9,
    recentSignal: "2 complaints this week",
    overallScore: 3,
    scoreCategories: { bribery: 2, hygiene: 3, waitTime: 1, equipment: 4, staff: 5 },
  },
  {
    id: "rabat-grand-poste",
    name: "La Grande Poste",
    category: "Public Office",
    address: "Avenue Mohammed V, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0195, longitude: -6.8362 },
    status: "verified",
    reviews: 72,
    complaints: 1,
    recentSignal: "Efficient mail processing",
    overallScore: 8,
    scoreCategories: { bribery: 9, hygiene: 8, waitTime: 6, equipment: 8, staff: 9 },
  },
  {
    id: "rabat-parlement",
    name: "Le Parlement du Maroc",
    category: "Public Office",
    address: "Avenue Mohammed V, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0182, longitude: -6.8368 },
    status: "priority",
    reviews: 154,
    complaints: 8,
    recentSignal: "High security checkpoint delays",
    overallScore: 4,
    scoreCategories: { bribery: 5, hygiene: 4, waitTime: 2, equipment: 5, staff: 4 },
  },
  {
    id: "hotel-balima",
    name: "Balima Minaret Suites",
    category: "Hotel",
    address: "Avenue Mohammed V, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0186, longitude: -6.8372 },
    status: "verified",
    reviews: 90,
    complaints: 0,
    recentSignal: "Renovated historical suites",
    overallScore: 9,
    scoreCategories: { bribery: 10, hygiene: 9, waitTime: 8, equipment: 9, staff: 9 },
  },
  {
    id: "mcdonalds-rabat-ville",
    name: "McDonald's Rabat Ville",
    category: "Restaurant",
    address: "Avenue Mohammed V, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0171, longitude: -6.8365 },
    status: "verified",
    reviews: 210,
    complaints: 3,
    recentSignal: "Busy during lunch hours",
    overallScore: 8,
    scoreCategories: { bribery: 10, hygiene: 8, waitTime: 7, equipment: 9, staff: 8 },
  },
  {
    id: "le-petit-beur",
    name: "Le Petit Beur",
    category: "Restaurant",
    address: "Rue Damas, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0180, longitude: -6.8350 },
    status: "verified",
    reviews: 88,
    complaints: 2,
    recentSignal: "Authentic tagine and couscous",
    overallScore: 7,
    scoreCategories: { bribery: 9, hygiene: 7, waitTime: 6, equipment: 7, staff: 8 },
  },
  {
    id: "boho-cafe",
    name: "Boho Cafe",
    category: "Cafe",
    address: "Rue Moulay Rachid, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0205, longitude: -6.8395 },
    status: "new",
    reviews: 12,
    complaints: 0,
    recentSignal: "Excellent specialty coffee",
    overallScore: 6,
    scoreCategories: { bribery: 8, hygiene: 7, waitTime: 5, equipment: 6, staff: 6 },
  },
  {
    id: "cozy-cafe",
    name: "Cozy Cafe",
    category: "Cafe",
    address: "Avenue Allal Ben Abdallah, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0165, longitude: -6.8340 },
    status: "watch",
    reviews: 43,
    complaints: 4,
    recentSignal: "WiFi instability reported",
    overallScore: 5,
    scoreCategories: { bribery: 7, hygiene: 5, waitTime: 4, equipment: 3, staff: 6 },
  },
  {
    id: "rabat-medina-market",
    name: "Bab El Had Medina Market",
    category: "Marketplace",
    address: "Avenue Hassan II, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0215, longitude: -6.8405 },
    status: "priority",
    reviews: 320,
    complaints: 18,
    recentSignal: "Congested walkways, watch for pickpockets",
    overallScore: 3,
    scoreCategories: { bribery: 4, hygiene: 2, waitTime: 3, equipment: 2, staff: 3 },
  },
  {
    id: "clinic-des-orangers",
    name: "Clinique des Orangers",
    category: "Clinic",
    address: "Rue d'Orangers, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0135, longitude: -6.8445 },
    status: "watch",
    reviews: 55,
    complaints: 6,
    recentSignal: "Long wait times at reception",
    overallScore: 4,
    scoreCategories: { bribery: 6, hygiene: 5, waitTime: 3, equipment: 5, staff: 4 },
  },
  {
    id: "lycee-descartes",
    name: "Lycée Descartes",
    category: "School",
    address: "Avenue Chellah, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0112, longitude: -6.8392 },
    status: "verified",
    reviews: 145,
    complaints: 2,
    recentSignal: "Strong academic rating",
    overallScore: 9,
    scoreCategories: { bribery: 10, hygiene: 9, waitTime: 8, equipment: 9, staff: 9 },
  },
  {
    id: "dar-naji",
    name: "Dar Naji Restaurant",
    category: "Restaurant",
    address: "Avenue Al Jazair, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0150, longitude: -6.8410 },
    status: "verified",
    reviews: 198,
    complaints: 5,
    recentSignal: "Popular traditional Moroccan dining",
    overallScore: 8,
    scoreCategories: { bribery: 9, hygiene: 8, waitTime: 7, equipment: 8, staff: 9 },
  },
  {
    id: "villa-mandarine",
    name: "Villa Mandarine",
    category: "Hotel",
    address: "Rue Ouled Bousbaa, Rabat",
    city: "Rabat",
    coordinates: { latitude: 33.9725, longitude: -6.8290 },
    status: "verified",
    reviews: 76,
    complaints: 1,
    recentSignal: "Tranquil orange grove gardens",
    overallScore: 9,
    scoreCategories: { bribery: 10, hygiene: 10, waitTime: 9, equipment: 9, staff: 9 },
  },
  {
    id: "mauresque-cafe",
    name: "Café Maure Kasbah",
    category: "Cafe",
    address: "Kasbah of the Udayas, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0322, longitude: -6.8315 },
    status: "verified",
    reviews: 112,
    complaints: 1,
    recentSignal: "Stunning river views, tea and pastries",
    overallScore: 8,
    scoreCategories: { bribery: 9, hygiene: 8, waitTime: 7, equipment: 8, staff: 8 },
  },
  {
    id: "national-library-rabat",
    name: "Bibliothèque Nationale",
    category: "Library",
    address: "Avenue Ibn Khaldoun, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0068, longitude: -6.8475 },
    status: "verified",
    reviews: 250,
    complaints: 3,
    recentSignal: "Excellent study environment and resources",
    overallScore: 8,
    scoreCategories: { bribery: 9, hygiene: 9, waitTime: 8, equipment: 8, staff: 8 },
  },
  {
    id: "rabat-art-museum",
    name: "Mohammed VI Art Museum",
    category: "Public Office",
    address: "Avenue Allal Ben Abdallah, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0155, longitude: -6.8360 },
    status: "verified",
    reviews: 84,
    complaints: 0,
    recentSignal: "Clean facilities and rich exhibits",
    overallScore: 9,
    scoreCategories: { bribery: 10, hygiene: 9, waitTime: 9, equipment: 9, staff: 8 },
  },
  {
    id: "cinema-renaissance",
    name: "Café Renaissance",
    category: "Cafe",
    address: "Avenue Mohammed V, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0177, longitude: -6.8369 },
    status: "verified",
    reviews: 49,
    complaints: 1,
    recentSignal: "Cultural hub for music and films",
    overallScore: 7,
    scoreCategories: { bribery: 9, hygiene: 7, waitTime: 7, equipment: 7, staff: 8 },
  },
  {
    id: "hasan-tower-plaza",
    name: "Hassan Tower Plaza",
    category: "Marketplace",
    address: "Boulevard Abi Regreg, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0240, longitude: -6.8225 },
    status: "priority",
    reviews: 412,
    complaints: 12,
    recentSignal: "High tourist traffic, access gates restricted",
    overallScore: 4,
    scoreCategories: { bribery: 5, hygiene: 4, waitTime: 3, equipment: 4, staff: 4 },
  },
  {
    id: "souk-el-sebbat",
    name: "Souk El Sebbat",
    category: "Marketplace",
    address: "Rue Souk Semmarine, Rabat Medina",
    city: "Rabat",
    coordinates: { latitude: 34.0268, longitude: -6.8365 },
    status: "new",
    reviews: 34,
    complaints: 2,
    recentSignal: "New pedestrian guides added",
    overallScore: 6,
    scoreCategories: { bribery: 7, hygiene: 5, waitTime: 6, equipment: 5, staff: 6 },
  },
  {
    id: "casablanca-tech-school",
    name: "Casablanca Tech School",
    category: "School",
    address: "Bourgogne District, Casablanca",
    city: "Casablanca",
    coordinates: { latitude: 33.5899, longitude: -7.6039 },
    status: "verified",
    reviews: 64,
    complaints: 2,
    recentSignal: "Top-rated by students",
    overallScore: 9,
    scoreCategories: { bribery: 9, hygiene: 9, waitTime: 8, equipment: 9, staff: 9 },
  },
  {
    id: "marrakesh-civic-office",
    name: "Marrakesh Civic Office",
    category: "Public Office",
    address: "Gueliz, Marrakesh",
    city: "Marrakesh",
    coordinates: { latitude: 31.6288, longitude: -7.9811 },
    status: "watch",
    reviews: 47,
    complaints: 5,
    recentSignal: "Queue delays reported",
    overallScore: 5,
    scoreCategories: { bribery: 6, hygiene: 5, waitTime: 3, equipment: 5, staff: 5 },
  },
  {
    id: "tangier-community-clinic",
    name: "Tangier Community Clinic",
    category: "Clinic",
    address: "Iberia Quarter, Tangier",
    city: "Tangier",
    coordinates: { latitude: 35.7595, longitude: -5.8340 },
    status: "new",
    reviews: 18,
    complaints: 1,
    recentSignal: "Recently added to the map",
    overallScore: 6,
    scoreCategories: { bribery: 7, hygiene: 6, waitTime: 5, equipment: 6, staff: 6 },
  },
  {
    id: "fez-central-library",
    name: "Fez Central Library",
    category: "Library",
    address: "Ville Nouvelle, Fez",
    city: "Fez",
    coordinates: { latitude: 34.0243, longitude: -5.0003 },
    status: "verified",
    reviews: 92,
    complaints: 0,
    recentSignal: "Clean record for 30 days",
    overallScore: 8,
    scoreCategories: { bribery: 10, hygiene: 8, waitTime: 8, equipment: 8, staff: 8 },
  },
  {
    id: "agadir-coastal-market",
    name: "Agadir Coastal Market",
    category: "Marketplace",
    address: "Corniche, Agadir",
    city: "Agadir",
    coordinates: { latitude: 30.4278, longitude: -9.5981 },
    status: "watch",
    reviews: 35,
    complaints: 4,
    recentSignal: "Access and pricing concerns",
    overallScore: 5,
    scoreCategories: { bribery: 4, hygiene: 5, waitTime: 4, equipment: 5, staff: 6 },
  },
  {
    id: "universite-mohammed-v-rabat",
    name: "Université Mohammed V",
    category: "University",
    address: "Avenue des Nations Unies, Agdal, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0042, longitude: -6.8550 },
    status: "verified",
    reviews: 245,
    complaints: 1,
    recentSignal: "Busy enrollment period",
    overallScore: 8,
    scoreCategories: { bribery: 9, hygiene: 8, waitTime: 6, equipment: 8, staff: 8 },
  },
  {
    id: "mosquee-hassan-ii-casablanca",
    name: "Mosquée Hassan II",
    category: "Mosque",
    address: "Boulevard de la Corniche, Casablanca",
    city: "Casablanca",
    coordinates: { latitude: 33.6085, longitude: -7.6326 },
    status: "new",
    reviews: 298,
    complaints: 0,
    recentSignal: "Beautiful morning views, high visitor count",
    overallScore: 7,
    scoreCategories: { bribery: 8, hygiene: 7, waitTime: 6, equipment: 7, staff: 7 },
  },
  {
    id: "gare-casa-voyageurs-casablanca",
    name: "Casablanca Voyageurs Station",
    category: "Train Station",
    address: "Boulevard Bahmad, Casablanca",
    city: "Casablanca",
    coordinates: { latitude: 33.5892, longitude: -7.5906 },
    status: "priority",
    reviews: 180,
    complaints: 11,
    recentSignal: "Ticket machine queues at peak hours",
    overallScore: 3,
    scoreCategories: { bribery: 5, hygiene: 3, waitTime: 2, equipment: 3, staff: 4 },
  },
  {
    id: "morocco-mall-casablanca",
    name: "Morocco Mall",
    category: "Market",
    address: "Boulevard de l'Océan Atlantique, Casablanca",
    city: "Casablanca",
    coordinates: { latitude: 33.5768, longitude: -7.7063 },
    status: "new",
    reviews: 220,
    complaints: 3,
    recentSignal: "Popular weekend shopping destination",
    overallScore: 7,
    scoreCategories: { bribery: 8, hygiene: 7, waitTime: 5, equipment: 7, staff: 7 },
  },
  {
    id: "attijariwafa-bank-casablanca",
    name: "Attijariwafa Bank Headquarters",
    category: "Bank",
    address: "Boulevard Moulay Youssef, Casablanca",
    city: "Casablanca",
    coordinates: { latitude: 33.5962, longitude: -7.6215 },
    status: "watch",
    reviews: 42,
    complaints: 7,
    recentSignal: "ATM out of service on Sunday",
    overallScore: 4,
    scoreCategories: { bribery: 6, hygiene: 5, waitTime: 4, equipment: 3, staff: 5 },
  },
  {
    id: "chu-ibn-rochd-casablanca",
    name: "CHU Ibn Rochd",
    category: "Hospital",
    address: "Rue des Hôpitaux, Casablanca",
    city: "Casablanca",
    coordinates: { latitude: 33.5775, longitude: -7.6234 },
    status: "priority",
    reviews: 115,
    complaints: 14,
    recentSignal: "High ER wait times reported",
    overallScore: 2,
    scoreCategories: { bribery: 3, hygiene: 2, waitTime: 1, equipment: 4, staff: 3 },
  },
  {
    id: "city-club-abdelmoumen-casablanca",
    name: "City Club Abdelmoumen",
    category: "Gym",
    address: "Boulevard Abdelmoumen, Casablanca",
    city: "Casablanca",
    coordinates: { latitude: 33.5790, longitude: -7.6180 },
    status: "watch",
    reviews: 95,
    complaints: 8,
    recentSignal: "Locker room maintenance requested",
    overallScore: 5,
    scoreCategories: { bribery: 7, hygiene: 4, waitTime: 5, equipment: 4, staff: 5 },
  },
  {
    id: "pharmacie-centrale-casablanca",
    name: "Pharmacie Centrale",
    category: "Pharmacy",
    address: "Avenue Mers Sultan, Casablanca",
    city: "Casablanca",
    coordinates: { latitude: 33.5855, longitude: -7.6130 },
    status: "new",
    reviews: 30,
    complaints: 1,
    recentSignal: "Well stocked with essential medicines",
    overallScore: 6,
    scoreCategories: { bribery: 8, hygiene: 6, waitTime: 6, equipment: 6, staff: 6 },
  },
  {
    id: "megarama-cinema-casablanca",
    name: "Megarama Cinema",
    category: "Cinema",
    address: "Boulevard de la Corniche, Ain Diab, Casablanca",
    city: "Casablanca",
    coordinates: { latitude: 33.6020, longitude: -7.6650 },
    status: "new",
    reviews: 145,
    complaints: 2,
    recentSignal: "New blockbuster releases drawing crowds",
    overallScore: 7,
    scoreCategories: { bribery: 8, hygiene: 7, waitTime: 6, equipment: 7, staff: 7 },
  },
  {
    id: "jardin-majorelle-marrakesh",
    name: "Jardin Majorelle",
    category: "Park",
    address: "Rue Yves Saint Laurent, Marrakesh",
    city: "Marrakesh",
    coordinates: { latitude: 31.6418, longitude: -8.0033 },
    status: "new",
    reviews: 280,
    complaints: 4,
    recentSignal: "Online booking required, long entry lines",
    overallScore: 6,
    scoreCategories: { bribery: 8, hygiene: 7, waitTime: 4, equipment: 7, staff: 6 },
  },
  {
    id: "cafe-des-epices-marrakesh",
    name: "Café des Épices",
    category: "Cafe",
    address: "Rahba Kedima, Medina, Marrakesh",
    city: "Marrakesh",
    coordinates: { latitude: 31.6280, longitude: -7.9865 },
    status: "new",
    reviews: 190,
    complaints: 1,
    recentSignal: "Excellent spice tea and rooftop views",
    overallScore: 7,
    scoreCategories: { bribery: 8, hygiene: 7, waitTime: 6, equipment: 7, staff: 7 },
  },
  {
    id: "gare-de-marrakech-marrakesh",
    name: "Gare de Marrakech",
    category: "Train Station",
    address: "Avenue Hassan II, Gueliz, Marrakesh",
    city: "Marrakesh",
    coordinates: { latitude: 31.6300, longitude: -8.0195 },
    status: "watch",
    reviews: 150,
    complaints: 5,
    recentSignal: "Taxi queue delays outside station",
    overallScore: 5,
    scoreCategories: { bribery: 6, hygiene: 5, waitTime: 3, equipment: 5, staff: 5 },
  },
  {
    id: "mosquee-koutoubia-marrakesh",
    name: "Koutoubia Mosque",
    category: "Mosque",
    address: "Medina, Marrakesh",
    city: "Marrakesh",
    coordinates: { latitude: 31.6238, longitude: -7.9936 },
    status: "new",
    reviews: 270,
    complaints: 0,
    recentSignal: "Iconic minaret landmark, clean plaza",
    overallScore: 7,
    scoreCategories: { bribery: 8, hygiene: 7, waitTime: 6, equipment: 7, staff: 7 },
  },
  {
    id: "la-mamounia-hotel-marrakesh",
    name: "La Mamounia",
    category: "Hotel",
    address: "Avenue Bab Jdid, Marrakesh",
    city: "Marrakesh",
    coordinates: { latitude: 31.6190, longitude: -7.9985 },
    status: "new",
    reviews: 210,
    complaints: 1,
    recentSignal: "World-class luxury gardens",
    overallScore: 7,
    scoreCategories: { bribery: 8, hygiene: 7, waitTime: 6, equipment: 8, staff: 7 },
  },
  {
    id: "universite-cadi-ayyad-marrakesh",
    name: "Université Cadi Ayyad",
    category: "University",
    address: "Boulevard Abdelkrim Al Khattabi, Marrakesh",
    city: "Marrakesh",
    coordinates: { latitude: 31.6475, longitude: -8.0140 },
    status: "priority",
    reviews: 130,
    complaints: 9,
    recentSignal: "Student registration congestion",
    overallScore: 4,
    scoreCategories: { bribery: 5, hygiene: 4, waitTime: 2, equipment: 5, staff: 4 },
  },
  {
    id: "universite-al-qarawiyyin-fez",
    name: "Université Al-Qarawiyyin",
    category: "University",
    address: "Medina, Fes",
    city: "Fes",
    coordinates: { latitude: 34.0647, longitude: -4.9736 },
    status: "new",
    reviews: 260,
    complaints: 0,
    recentSignal: "Historic library and courtyard",
    overallScore: 7,
    scoreCategories: { bribery: 8, hygiene: 7, waitTime: 6, equipment: 7, staff: 7 },
  },
  {
    id: "gare-de-fes-fes",
    name: "Gare de Fès",
    category: "Train Station",
    address: "Boulevard des Almohades, Fes",
    city: "Fes",
    coordinates: { latitude: 34.0320, longitude: -5.0080 },
    status: "watch",
    reviews: 88,
    complaints: 6,
    recentSignal: "Renovation works in progress",
    overallScore: 5,
    scoreCategories: { bribery: 6, hygiene: 5, waitTime: 4, equipment: 4, staff: 5 },
  },
  {
    id: "bab-boujloud-market-fes",
    name: "Bab Boujloud Market",
    category: "Market",
    address: "Place Bab Boujloud, Medina, Fes",
    city: "Fes",
    coordinates: { latitude: 34.0615, longitude: -4.9825 },
    status: "priority",
    reviews: 175,
    complaints: 10,
    recentSignal: "Very crowded corridors, watch for tourists",
    overallScore: 3,
    scoreCategories: { bribery: 4, hygiene: 3, waitTime: 2, equipment: 3, staff: 4 },
  },
  {
    id: "gare-tanger-ville-tangier",
    name: "Tangier Ville Railway Station",
    category: "Train Station",
    address: "Boulevard Mohamed V, Tangier",
    city: "Tangier",
    coordinates: { latitude: 35.7725, longitude: -5.7980 },
    status: "new",
    reviews: 165,
    complaints: 3,
    recentSignal: "High-speed Al Boraq arrivals running on time",
    overallScore: 7,
    scoreCategories: { bribery: 8, hygiene: 7, waitTime: 6, equipment: 7, staff: 7 },
  },
  {
    id: "cafe-hafa-tangier",
    name: "Café Hafa",
    category: "Cafe",
    address: "Rue Hafa, Tangier",
    city: "Tangier",
    coordinates: { latitude: 35.7912, longitude: -5.8218 },
    status: "new",
    reviews: 205,
    complaints: 2,
    recentSignal: "Stunning views of the Strait of Gibraltar",
    overallScore: 7,
    scoreCategories: { bribery: 8, hygiene: 7, waitTime: 6, equipment: 7, staff: 7 },
  },
  {
    id: "port-tanger-ville-tangier",
    name: "Port de Tanger Ville",
    category: "Public Office",
    address: "Avenue d'Espagne, Tangier",
    city: "Tangier",
    coordinates: { latitude: 35.7865, longitude: -5.8080 },
    status: "priority",
    reviews: 140,
    complaints: 12,
    recentSignal: "Customs check queue times increased",
    overallScore: 3,
    scoreCategories: { bribery: 4, hygiene: 4, waitTime: 2, equipment: 3, staff: 3 },
  },
  {
    id: "souk-el-had-market-agadir",
    name: "Souk El Had",
    category: "Market",
    address: "Rue 2 Mars, Agadir",
    city: "Agadir",
    coordinates: { latitude: 30.4120, longitude: -9.5815 },
    status: "watch",
    reviews: 290,
    complaints: 8,
    recentSignal: "Massive market layout, parking challenges",
    overallScore: 5,
    scoreCategories: { bribery: 6, hygiene: 5, waitTime: 4, equipment: 5, staff: 5 },
  },
  {
    id: "aeroport-al-massira-agadir",
    name: "Airport Al Massira",
    category: "Airport",
    address: "Hachach, Agadir",
    city: "Agadir",
    coordinates: { latitude: 30.3250, longitude: -9.4120 },
    status: "new",
    reviews: 110,
    complaints: 4,
    recentSignal: "Smooth check-in, passenger queues normal",
    overallScore: 6,
    scoreCategories: { bribery: 8, hygiene: 6, waitTime: 5, equipment: 6, staff: 6 },
  },

  // ── RABAT (expanded for demo) ──────────────────────────────────
  {
    id: "gare-rabat-agdal",
    name: "Gare Rabat-Agdal",
    category: "Train Station",
    address: "Avenue Mohamed Triki, Agdal, Rabat 10000",
    city: "Rabat",
    coordinates: { latitude: 34.0013, longitude: -6.8575 },
    status: "verified",
    reviews: 387,
    complaints: 8,
    recentSignal: "Long queues during peak hours at ticket counters",
    overallScore: 7,
    scoreCategories: { bribery: 8, hygiene: 7, waitTime: 5, equipment: 8, staff: 7 },
  },
  {
    id: "gare-rabat-ville",
    name: "Gare Rabat-Ville",
    category: "Train Station",
    address: "Avenue Mohammed V, Centre Ville, Rabat 10000",
    city: "Rabat",
    coordinates: { latitude: 34.0160, longitude: -6.8360 },
    status: "verified",
    reviews: 342,
    complaints: 6,
    recentSignal: "Heritage station in need of maintenance; ticket machines often out of service",
    overallScore: 7,
    scoreCategories: { bribery: 8, hygiene: 6, waitTime: 5, equipment: 6, staff: 7 },
  },
  {
    id: "chu-ibn-sina",
    name: "CHU Ibn Sina",
    category: "Hospital",
    address: "Avenue Bettouga, Institut, Rabat 10999",
    city: "Rabat",
    coordinates: { latitude: 33.9839, longitude: -6.8504 },
    status: "priority",
    reviews: 398,
    complaints: 14,
    recentSignal: "Emergency department overcrowding; average wait exceeding 4 hours",
    overallScore: 5,
    scoreCategories: { bribery: 4, hygiene: 5, waitTime: 3, equipment: 6, staff: 5 },
  },
  {
    id: "hopital-cheikh-zaid",
    name: "Hôpital Universitaire International Cheikh Zaïd",
    category: "Hospital",
    address: "Avenue Allal El Fassi, Madinat Al Irfane, Hay Riad, Rabat",
    city: "Rabat",
    coordinates: { latitude: 33.9775, longitude: -6.8697 },
    status: "verified",
    reviews: 276,
    complaints: 5,
    recentSignal: "Modern facility; public wing has longer wait times than private",
    overallScore: 7,
    scoreCategories: { bribery: 7, hygiene: 8, waitTime: 5, equipment: 9, staff: 7 },
  },
  {
    id: "hopital-moulay-youssef",
    name: "Centre Hospitalier Régional Moulay Youssef",
    category: "Hospital",
    address: "Avenue Mustapha Assayeh 21, Agdal, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0108, longitude: -6.8500 },
    status: "watch",
    reviews: 215,
    complaints: 11,
    recentSignal: "Respiratory medicine understaffed; lab results delayed 48 hours",
    overallScore: 5,
    scoreCategories: { bribery: 5, hygiene: 5, waitTime: 4, equipment: 5, staff: 5 },
  },
  {
    id: "hopital-enfants-chu",
    name: "Hôpital des Enfants du CHU Ibn Sina",
    category: "Hospital",
    address: "Avenue Ibn Rochd, Rabat",
    city: "Rabat",
    coordinates: { latitude: 33.9825, longitude: -6.8532 },
    status: "watch",
    reviews: 198,
    complaints: 14,
    recentSignal: "Overcrowded pediatric wards reported",
    overallScore: 5,
    scoreCategories: { bribery: 4, hygiene: 5, waitTime: 3, equipment: 6, staff: 6 },
  },
  {
    id: "arrondissement-hassan",
    name: "Mairie de l'Arrondissement Hassan",
    category: "Public Office",
    address: "Avenue Moulay Ismail, Hassan, Rabat 10020",
    city: "Rabat",
    coordinates: { latitude: 34.0165, longitude: -6.8328 },
    status: "priority",
    reviews: 189,
    complaints: 13,
    recentSignal: "Excessive paperwork for simple administrative certificates",
    overallScore: 4,
    scoreCategories: { bribery: 3, hygiene: 5, waitTime: 3, equipment: 4, staff: 4 },
  },
  {
    id: "caidariat-hay-riad",
    name: "Caidariat de Hay Riad",
    category: "Public Office",
    address: "Hay Riad, Quartier Vita, Rabat 10100",
    city: "Rabat",
    coordinates: { latitude: 33.9608, longitude: -6.8720 },
    status: "new",
    reviews: 94,
    complaints: 4,
    recentSignal: "Recently opened office; generally efficient service",
    overallScore: 6,
    scoreCategories: { bribery: 6, hygiene: 6, waitTime: 5, equipment: 6, staff: 6 },
  },
  {
    id: "wilaya-rabat",
    name: "Wilaya de Rabat-Salé-Kénitra",
    category: "Public Office",
    address: "Avenue Ibn Khaldoun, Agdal, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0080, longitude: -6.8430 },
    status: "priority",
    reviews: 320,
    complaints: 18,
    recentSignal: "Long processing times for land registry and civil status documents",
    overallScore: 3,
    scoreCategories: { bribery: 3, hygiene: 4, waitTime: 2, equipment: 4, staff: 3 },
  },
  {
    id: "poste-agdal",
    name: "La Poste Agdal",
    category: "Post Office",
    address: "Angle Boulevard Omar Ibn El Khattab et Boulevard Dadés, Agdal, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0010, longitude: -6.8550 },
    status: "verified",
    reviews: 231,
    complaints: 7,
    recentSignal: "Package delivery notifications unreliable; slow during lunch",
    overallScore: 6,
    scoreCategories: { bribery: 7, hygiene: 6, waitTime: 4, equipment: 6, staff: 6 },
  },
  {
    id: "poste-hassan",
    name: "La Poste Hassan",
    category: "Post Office",
    address: "Avenue Hassan II, Hassan, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0175, longitude: -6.8345 },
    status: "watch",
    reviews: 178,
    complaints: 9,
    recentSignal: "Counter service slow; frequent system outages",
    overallScore: 5,
    scoreCategories: { bribery: 6, hygiene: 5, waitTime: 3, equipment: 4, staff: 5 },
  },
  {
    id: "lycee-lalla-nezha",
    name: "Lycée Lalla Nezha",
    category: "School",
    address: "Avenue Jean Jaurès, Les Orangers, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0190, longitude: -6.8380 },
    status: "watch",
    reviews: 167,
    complaints: 9,
    recentSignal: "Overcrowded classrooms with 45+ students per section",
    overallScore: 5,
    scoreCategories: { bribery: 6, hygiene: 5, waitTime: 5, equipment: 4, staff: 6 },
  },
  {
    id: "lycee-lalla-kenza",
    name: "Lycée Lalla Kenza",
    category: "School",
    address: "103 Avenue Abdelkrim El Khattabi, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0130, longitude: -6.8450 },
    status: "new",
    reviews: 112,
    complaints: 3,
    recentSignal: "Recently renovated facilities; new computer lab installed",
    overallScore: 7,
    scoreCategories: { bribery: 7, hygiene: 7, waitTime: 6, equipment: 7, staff: 7 },
  },
  {
    id: "lycee-andre-malraux",
    name: "Lycée André Malraux",
    category: "School",
    address: "Hay Riad, Rabat",
    city: "Rabat",
    coordinates: { latitude: 33.9701, longitude: -6.8267 },
    status: "verified",
    reviews: 156,
    complaints: 3,
    recentSignal: "French international school serving 1800 students",
    overallScore: 8,
    scoreCategories: { bribery: 1, hygiene: 8, waitTime: 7, equipment: 8, staff: 8 },
  },
  {
    id: "lycee-moulay-youssef",
    name: "Lycée Moulay Youssef",
    category: "School",
    address: "Avenue Allal El Fassi, Agdal, Rabat",
    city: "Rabat",
    coordinates: { latitude: 33.9912, longitude: -6.8545 },
    status: "new",
    reviews: 89,
    complaints: 5,
    recentSignal: "Public high school needing infrastructure upgrades",
    overallScore: 5,
    scoreCategories: { bribery: 4, hygiene: 5, waitTime: 5, equipment: 4, staff: 6 },
  },
  {
    id: "faculte-sciences-rabat",
    name: "Faculté des Sciences de Rabat",
    category: "University",
    address: "4 Avenue Ibn Battouta, Agdal, Rabat 10000",
    city: "Rabat",
    coordinates: { latitude: 34.0030, longitude: -6.8530 },
    status: "verified",
    reviews: 245,
    complaints: 6,
    recentSignal: "Aging lecture halls with poor ventilation; labs need upgrades",
    overallScore: 6,
    scoreCategories: { bribery: 7, hygiene: 5, waitTime: 6, equipment: 5, staff: 6 },
  },
  {
    id: "faculte-medecine-dentaire",
    name: "Faculté de Médecine Dentaire de Rabat",
    category: "University",
    address: "Avenue des Nations Unies, Agdal, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0050, longitude: -6.8520 },
    status: "new",
    reviews: 89,
    complaints: 2,
    recentSignal: "Modern dental clinics with supervised student treatments",
    overallScore: 7,
    scoreCategories: { bribery: 8, hygiene: 8, waitTime: 6, equipment: 8, staff: 7 },
  },
  {
    id: "faculte-medecine-pharmacie",
    name: "Faculté de Médecine et de Pharmacie de Rabat",
    category: "University",
    address: "Avenue Med Belarbi El Alaoui, Rabat",
    city: "Rabat",
    coordinates: { latitude: 33.9856, longitude: -6.8523 },
    status: "verified",
    reviews: 178,
    complaints: 6,
    recentSignal: "Leading medical education institution in Morocco",
    overallScore: 7,
    scoreCategories: { bribery: 2, hygiene: 7, waitTime: 5, equipment: 8, staff: 7 },
  },
  {
    id: "faculte-sciences-juridiques",
    name: "Faculté des Sciences Juridiques, Économiques et Sociales",
    category: "University",
    address: "Avenue des Nations Unies, Agdal, Rabat",
    city: "Rabat",
    coordinates: { latitude: 33.9952, longitude: -6.8567 },
    status: "new",
    reviews: 134,
    complaints: 4,
    recentSignal: "Law and economics faculty with high enrollment",
    overallScore: 6,
    scoreCategories: { bribery: 3, hygiene: 6, waitTime: 5, equipment: 6, staff: 7 },
  },
  {
    id: "clinique-agdal",
    name: "Clinique Agdal",
    category: "Clinic",
    address: "6 Place Talha, Avenue Ibn Sina, Agdal, Rabat",
    city: "Rabat",
    coordinates: { latitude: 33.9959, longitude: -6.8510 },
    status: "verified",
    reviews: 298,
    complaints: 3,
    recentSignal: "Private clinic with modern equipment; billing transparency concerns",
    overallScore: 8,
    scoreCategories: { bribery: 8, hygiene: 9, waitTime: 7, equipment: 9, staff: 8 },
  },
  {
    id: "marche-central-rabat",
    name: "Marché Central de Rabat",
    category: "Marketplace",
    address: "Rue Nouayel, Centre Ville, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0180, longitude: -6.8310 },
    status: "watch",
    reviews: 312,
    complaints: 10,
    recentSignal: "Hygiene concerns in fish section; weight scale accuracy questioned",
    overallScore: 6,
    scoreCategories: { bribery: 6, hygiene: 4, waitTime: 7, equipment: 5, staff: 6 },
  },
  {
    id: "grande-pharmacie-rabat",
    name: "La Grande Pharmacie",
    category: "Pharmacy",
    address: "17 Rue Abou Faris El Marini, Hassan, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0150, longitude: -6.8340 },
    status: "verified",
    reviews: 178,
    complaints: 4,
    recentSignal: "24-hour service; occasional stockouts on subsidized drugs",
    overallScore: 7,
    scoreCategories: { bribery: 8, hygiene: 8, waitTime: 6, equipment: 7, staff: 7 },
  },
  {
    id: "pharmacie-centrale-hassan",
    name: "Pharmacie Centrale Hassan",
    category: "Pharmacy",
    address: "Avenue Hassan II, Centre Ville, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0180, longitude: -6.8320 },
    status: "verified",
    reviews: 203,
    complaints: 3,
    recentSignal: "Well-staffed central location; good pharmacist consultation",
    overallScore: 8,
    scoreCategories: { bribery: 9, hygiene: 8, waitTime: 7, equipment: 8, staff: 8 },
  },
  {
    id: "pharmacie-ibn-khatab",
    name: "Pharmacie Ibn Khattab",
    category: "Pharmacy",
    address: "Arribat Center, Avenue Al Abtal, Agdal, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0033, longitude: -6.8425 },
    status: "verified",
    reviews: 87,
    complaints: 2,
    recentSignal: "Convenient pharmacy in shopping center",
    overallScore: 7,
    scoreCategories: { bribery: 1, hygiene: 8, waitTime: 7, equipment: 7, staff: 8 },
  },
  {
    id: "pharmacie-alam-24h",
    name: "Pharmacie ALAM 24h",
    category: "Pharmacy",
    address: "Avenue de France, Agdal, Rabat",
    city: "Rabat",
    coordinates: { latitude: 33.9987, longitude: -6.8512 },
    status: "watch",
    reviews: 65,
    complaints: 3,
    recentSignal: "24-hour pharmacy serving night emergencies",
    overallScore: 7,
    scoreCategories: { bribery: 1, hygiene: 7, waitTime: 8, equipment: 7, staff: 7 },
  },
  {
    id: "bmce-bank-agdal",
    name: "BMCE Bank of Africa — Agdal",
    category: "Bank",
    address: "Avenue Ibn Sina, Agdal, Rabat",
    city: "Rabat",
    coordinates: { latitude: 33.9965, longitude: -6.8556 },
    status: "verified",
    reviews: 112,
    complaints: 7,
    recentSignal: "Major bank branch with digital services",
    overallScore: 6,
    scoreCategories: { bribery: 3, hygiene: 7, waitTime: 5, equipment: 7, staff: 6 },
  },
  {
    id: "banque-populaire-agdal",
    name: "Banque Populaire — Agence Rabat Agdal",
    category: "Bank",
    address: "Avenue de France, Agdal, Rabat",
    city: "Rabat",
    coordinates: { latitude: 33.9978, longitude: -6.8534 },
    status: "watch",
    reviews: 98,
    complaints: 9,
    recentSignal: "Long queues reported during month-end",
    overallScore: 5,
    scoreCategories: { bribery: 4, hygiene: 6, waitTime: 3, equipment: 6, staff: 5 },
  },
  {
    id: "cih-bank-rabat",
    name: "CIH Bank — Agence Rabat",
    category: "Bank",
    address: "Avenue Annakhil, Hay Riad, Rabat",
    city: "Rabat",
    coordinates: { latitude: 33.9789, longitude: -6.8612 },
    status: "new",
    reviews: 76,
    complaints: 4,
    recentSignal: "Modern banking with mortgage services",
    overallScore: 6,
    scoreCategories: { bribery: 2, hygiene: 7, waitTime: 6, equipment: 8, staff: 6 },
  },
  {
    id: "complexe-sportif-prince-moulay-abdellah",
    name: "Complexe Sportif Prince Moulay Abdellah",
    category: "Gym",
    address: "Hay Riad, Rabat",
    city: "Rabat",
    coordinates: { latitude: 33.9670, longitude: -6.8650 },
    status: "verified",
    reviews: 267,
    complaints: 5,
    recentSignal: "Major renovations for AFCON 2025; limited public access during events",
    overallScore: 7,
    scoreCategories: { bribery: 7, hygiene: 7, waitTime: 7, equipment: 9, staff: 7 },
  },
  {
    id: "fitness-park-arribat",
    name: "Fitness Park — Arribat Center",
    category: "Gym",
    address: "Arribat Center, Avenue Al Abtal, Agdal, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0033, longitude: -6.8421 },
    status: "verified",
    reviews: 145,
    complaints: 2,
    recentSignal: "Premium gym with modern equipment",
    overallScore: 8,
    scoreCategories: { bribery: 1, hygiene: 9, waitTime: 7, equipment: 9, staff: 8 },
  },
  {
    id: "megarama-rabat",
    name: "Megarama Rabat — Arribat Center",
    category: "Cinema",
    address: "Arribat Center, Avenue Al Abtal, Agdal, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0034, longitude: -6.8418 },
    status: "new",
    reviews: 234,
    complaints: 5,
    recentSignal: "New IMAX with Laser theater opened December 2025",
    overallScore: 8,
    scoreCategories: { bribery: 1, hygiene: 8, waitTime: 7, equipment: 9, staff: 7 },
  },
  {
    id: "jardin-exotique-bouknadel",
    name: "Les Jardins Exotiques de Bouknadel",
    category: "Park",
    address: "Km 13, Route de Rabat, Salé",
    city: "Rabat",
    coordinates: { latitude: 34.0625, longitude: -6.7856 },
    status: "verified",
    reviews: 312,
    complaints: 4,
    recentSignal: "Popular botanical garden attracting tourists",
    overallScore: 8,
    scoreCategories: { bribery: 1, hygiene: 8, waitTime: 7, equipment: 7, staff: 8 },
  },
  {
    id: "jardin-essais-botaniques",
    name: "Jardin d'Essais Botaniques de Rabat",
    category: "Park",
    address: "Avenue Annasr, Agdal, Rabat",
    city: "Rabat",
    coordinates: { latitude: 33.9845, longitude: -6.8589 },
    status: "verified",
    reviews: 187,
    complaints: 3,
    recentSignal: "17-hectare botanical garden since 1914",
    overallScore: 7,
    scoreCategories: { bribery: 1, hygiene: 7, waitTime: 8, equipment: 7, staff: 7 },
  },
  {
    id: "mosquee-assounna",
    name: "Mosquée Assounna",
    category: "Mosque",
    address: "Quartier de la Kasbah, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0190, longitude: -6.8390 },
    status: "verified",
    reviews: 156,
    complaints: 1,
    recentSignal: "Well-maintained historic mosque commissioned in 1785",
    overallScore: 9,
    scoreCategories: { bribery: 10, hygiene: 9, waitTime: 8, equipment: 7, staff: 9 },
  },
  {
    id: "chellah-ruins",
    name: "Site Archéologique de Chellah",
    category: "Park",
    address: "Rue Tour Hassan, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0235, longitude: -6.8350 },
    status: "verified",
    reviews: 245,
    complaints: 3,
    recentSignal: "Historic necropolis; stork colony a major attraction",
    overallScore: 8,
    scoreCategories: { bribery: 1, hygiene: 8, waitTime: 7, equipment: 7, staff: 8 },
  },
  {
    id: "kabdana-market-rabat",
    name: "Marché Kabdana",
    category: "Marketplace",
    address: "Hay Kabdana, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0250, longitude: -6.8280 },
    status: "priority",
    reviews: 180,
    complaints: 12,
    recentSignal: "Congested aisles; vendor licensing disputes reported",
    overallScore: 4,
    scoreCategories: { bribery: 4, hygiene: 3, waitTime: 4, equipment: 3, staff: 4 },
  },
];

export const statusStyles: Record<Establishment["status"], string> = {
  verified: "bg-emerald-100 text-emerald-700",
  watch: "bg-amber-100 text-amber-800",
  new: "bg-sky-100 text-sky-700",
  priority: "bg-rose-100 text-rose-700",
};

export const statusLabels: Record<Establishment["status"], string> = {
  verified: "Verified",
  watch: "Watchlist",
  new: "New",
  priority: "Priority",
};

export const mapCenter = {
  latitude: 34.02202576348649,
  longitude: -6.837746710969857,
};

export const mapCamera = {
  coordinates: mapCenter,
  zoom: 6.5,
};

export const mapProperties = {
  selectionEnabled: false,
};

export const categoryColors: Record<string, string> = {
  Hospital: "red",
  School: "#4CAF50",
  Marketplace: "green",
  Market: "green",
  "Public Office": "purple",
  Clinic: "orange",
  Library: "teal",
  Restaurant: "orange",
  Cafe: "teal",
  Hotel: "blue",
  University: "#2196F3",
  Government: "#9C27B0",
  Shop: "#FF9800",
  Pharmacy: "#00BCD4",
  Bank: "#607D8B",
  Gym: "#F44336",
  Cinema: "#E91E63",
  Park: "#8BC34A",
  Mosque: "#795548",
  "Train Station": "#3F51B5",
  "Bus Station": "#009688",
  Airport: "#03A9F4",
  "Post Office": "#FF5722",
};

export const markers = establishments.map((item) => ({
  id: item.id,
  coordinates: item.coordinates,
  showCallout: false,
  zIndex: item.status === "priority" ? 10 : 1,
  tintColor:
    item.overallScore !== undefined && item.overallScore >= 7
      ? "#22C55E"
      : item.overallScore !== undefined && item.overallScore >= 4
        ? "#EAB308"
        : "#EF4444",
}));
