import type { Establishment } from "../types";

export const establishments: Establishment[] = [
  {
    id: "rabat-central-hospital",
    name: "Rabat Central Hospital",
    category: "Hospital",
    address: "Avenue Al Maarif, Rabat",
    city: "Rabat",
    coordinates: { latitude: 33.9902, longitude: -6.8436 },
    status: "priority",
    reviews: 128,
    complaints: 9,
    recentSignal: "2 complaints this week",
  },
  {
    id: "rabat-grand-poste",
    name: "La Grande Poste",
    category: "Public Office",
    address: "Avenue Mohammed V, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0195, longitude: -6.8362 },
    status: "verified",
    reviews: 72,
    complaints: 1,
    recentSignal: "Efficient mail processing",
  },
  {
    id: "rabat-parlement",
    name: "Le Parlement du Maroc",
    category: "Public Office",
    address: "Avenue Mohammed V, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0182, longitude: -6.8368 },
    status: "priority",
    reviews: 154,
    complaints: 8,
    recentSignal: "High security checkpoint delays",
  },
  {
    id: "hotel-balima",
    name: "Balima Minaret Suites",
    category: "Hotel",
    address: "Avenue Mohammed V, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0186, longitude: -6.8372 },
    status: "verified",
    reviews: 90,
    complaints: 0,
    recentSignal: "Renovated historical suites",
  },
  {
    id: "mcdonalds-rabat-ville",
    name: "McDonald's Rabat Ville",
    category: "Restaurant",
    address: "Avenue Mohammed V, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0171, longitude: -6.8365 },
    status: "verified",
    reviews: 210,
    complaints: 3,
    recentSignal: "Busy during lunch hours",
  },
  {
    id: "le-petit-beur",
    name: "Le Petit Beur",
    category: "Restaurant",
    address: "Rue Damas, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0180, longitude: -6.8350 },
    status: "verified",
    reviews: 88,
    complaints: 2,
    recentSignal: "Authentic tagine and couscous",
  },
  {
    id: "boho-cafe",
    name: "Boho Cafe",
    category: "Cafe",
    address: "Rue Moulay Rachid, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0205, longitude: -6.8395 },
    status: "new",
    reviews: 12,
    complaints: 0,
    recentSignal: "Excellent specialty coffee",
  },
  {
    id: "cozy-cafe",
    name: "Cozy Cafe",
    category: "Cafe",
    address: "Avenue Allal Ben Abdallah, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0165, longitude: -6.8340 },
    status: "watch",
    reviews: 43,
    complaints: 4,
    recentSignal: "WiFi instability reported",
  },
  {
    id: "rabat-medina-market",
    name: "Bab El Had Medina Market",
    category: "Marketplace",
    address: "Avenue Hassan II, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0215, longitude: -6.8405 },
    status: "priority",
    reviews: 320,
    complaints: 18,
    recentSignal: "Congested walkways, watch for pickpockets",
  },
  {
    id: "clinic-des-orangers",
    name: "Clinique des Orangers",
    category: "Clinic",
    address: "Rue d'Orangers, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0135, longitude: -6.8445 },
    status: "watch",
    reviews: 55,
    complaints: 6,
    recentSignal: "Long wait times at reception",
  },
  {
    id: "lycee-descartes",
    name: "Lycée Descartes",
    category: "School",
    address: "Avenue Chellah, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0112, longitude: -6.8392 },
    status: "verified",
    reviews: 145,
    complaints: 2,
    recentSignal: "Strong academic rating",
  },
  {
    id: "dar-naji",
    name: "Dar Naji Restaurant",
    category: "Restaurant",
    address: "Avenue Al Jazair, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0150, longitude: -6.8410 },
    status: "verified",
    reviews: 198,
    complaints: 5,
    recentSignal: "Popular traditional Moroccan dining",
  },
  {
    id: "villa-mandarine",
    name: "Villa Mandarine",
    category: "Hotel",
    address: "Rue Ouled Bousbaa, Rabat",
    city: "Rabat",
    coordinates: { latitude: 33.9725, longitude: -6.8290 },
    status: "verified",
    reviews: 76,
    complaints: 1,
    recentSignal: "Tranquil orange grove gardens",
  },
  {
    id: "mauresque-cafe",
    name: "Café Maure Kasbah",
    category: "Cafe",
    address: "Kasbah of the Udayas, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0322, longitude: -6.8315 },
    status: "verified",
    reviews: 112,
    complaints: 1,
    recentSignal: "Stunning river views, tea and pastries",
  },
  {
    id: "national-library-rabat",
    name: "Bibliothèque Nationale",
    category: "Library",
    address: "Avenue Ibn Khaldoun, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0068, longitude: -6.8475 },
    status: "verified",
    reviews: 250,
    complaints: 3,
    recentSignal: "Excellent study environment and resources",
  },
  {
    id: "rabat-art-museum",
    name: "Mohammed VI Art Museum",
    category: "Public Office",
    address: "Avenue Allal Ben Abdallah, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0155, longitude: -6.8360 },
    status: "verified",
    reviews: 84,
    complaints: 0,
    recentSignal: "Clean facilities and rich exhibits",
  },
  {
    id: "cinema-renaissance",
    name: "Café Renaissance",
    category: "Cafe",
    address: "Avenue Mohammed V, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0177, longitude: -6.8369 },
    status: "verified",
    reviews: 49,
    complaints: 1,
    recentSignal: "Cultural hub for music and films",
  },
  {
    id: "hasan-tower-plaza",
    name: "Hassan Tower Plaza",
    category: "Marketplace",
    address: "Boulevard Abi Regreg, Rabat",
    city: "Rabat",
    coordinates: { latitude: 34.0240, longitude: -6.8225 },
    status: "priority",
    reviews: 412,
    complaints: 12,
    recentSignal: "High tourist traffic, access gates restricted",
  },
  {
    id: "souk-el-sebbat",
    name: "Souk El Sebbat",
    category: "Marketplace",
    address: "Rue Souk Semmarine, Rabat Medina",
    city: "Rabat",
    coordinates: { latitude: 34.0268, longitude: -6.8365 },
    status: "new",
    reviews: 34,
    complaints: 2,
    recentSignal: "New pedestrian guides added",
  },
  {
    id: "casablanca-tech-school",
    name: "Casablanca Tech School",
    category: "School",
    address: "Bourgogne District, Casablanca",
    city: "Casablanca",
    coordinates: { latitude: 33.5899, longitude: -7.6039 },
    status: "verified",
    reviews: 64,
    complaints: 2,
    recentSignal: "Top-rated by students",
  },
  {
    id: "marrakesh-civic-office",
    name: "Marrakesh Civic Office",
    category: "Public Office",
    address: "Gueliz, Marrakesh",
    city: "Marrakesh",
    coordinates: { latitude: 31.6288, longitude: -7.9811 },
    status: "watch",
    reviews: 47,
    complaints: 5,
    recentSignal: "Queue delays reported",
  },
  {
    id: "tangier-community-clinic",
    name: "Tangier Community Clinic",
    category: "Clinic",
    address: "Iberia Quarter, Tangier",
    city: "Tangier",
    coordinates: { latitude: 35.7595, longitude: -5.834 },
    status: "new",
    reviews: 18,
    complaints: 1,
    recentSignal: "Recently added to the map",
  },
  {
    id: "fez-central-library",
    name: "Fez Central Library",
    category: "Library",
    address: "Ville Nouvelle, Fez",
    city: "Fez",
    coordinates: { latitude: 34.0243, longitude: -5.0003 },
    status: "verified",
    reviews: 92,
    complaints: 0,
    recentSignal: "Clean record for 30 days",
  },
  {
    id: "agadir-coastal-market",
    name: "Agadir Coastal Market",
    category: "Marketplace",
    address: "Corniche, Agadir",
    city: "Agadir",
    coordinates: { latitude: 30.4278, longitude: -9.5981 },
    status: "watch",
    reviews: 35,
    complaints: 4,
    recentSignal: "Access and pricing concerns",
  },
];

export const statusStyles: Record<Establishment["status"], string> = {
  verified: "bg-emerald-100 text-emerald-700",
  watch: "bg-amber-100 text-amber-800",
  new: "bg-sky-100 text-sky-700",
  priority: "bg-rose-100 text-rose-700",
};

export const statusLabels: Record<Establishment["status"], string> = {
  verified: "Verified",
  watch: "Watchlist",
  new: "New",
  priority: "Priority",
};

export const mapCenter = {
  latitude: 34.02202576348649,
  longitude: -6.837746710969857,
};

export const mapCamera = {
  coordinates: mapCenter,
  zoom: 6.5,
};

export const mapProperties = {
  selectionEnabled: true,
};

export const categoryColors: Record<string, string> = {
  Hospital: "red",
  School: "blue",
  Marketplace: "green",
  "Public Office": "purple",
  Clinic: "orange",
  Library: "teal",
  Restaurant: "orange",
  Cafe: "teal",
  Hotel: "blue",
};

export const markers = establishments.map((item) => ({
  id: item.id,
  coordinates: item.coordinates,
  showCallout: false,
  zIndex: item.status === "priority" ? 10 : 1,
  tintColor: categoryColors[item.category] || "red",
}));
