import { MapReview } from "./types";

export const latestReviews: MapReview[] = [
  {
    id: "rev-1",
    establishmentId: "rabat-central-hospital",
    establishmentName: "Rabat Central Hospital",
    category: "Hospital",
    score: 2,
    snippet: "Waited 4 hours in the emergency ward. Nurse demanded 200 MAD to skip the queue.",
    author: "Citizen #4821",
    relativeTime: "12 min ago",
    status: "priority",
  },
  {
    id: "rev-2",
    establishmentId: "rabat-medina-market",
    establishmentName: "Bab El Had Medina Market",
    category: "Marketplace",
    score: 3,
    snippet: "Congested walkways near the spice section. Saw someone pickpocketing.",
    author: "Citizen #3019",
    relativeTime: "28 min ago",
    status: "priority",
  },
  {
    id: "rev-3",
    establishmentId: "rabat-parlement",
    establishmentName: "Le Parlement du Maroc",
    category: "Public Office",
    score: 4,
    snippet: "Security checkpoint was painfully slow. 45 min just to enter the building.",
    author: "Citizen #1577",
    relativeTime: "1 hr ago",
    status: "priority",
  },
  {
    id: "rev-4",
    establishmentId: "clinic-des-orangers",
    establishmentName: "Clinique des Orangers",
    category: "Clinic",
    score: 4,
    snippet: "Reception desk unstaffed for 30 minutes. Multiple patients left waiting.",
    author: "Citizen #2903",
    relativeTime: "2 hr ago",
    status: "watch",
  },
  {
    id: "rev-5",
    establishmentId: "hotel-balima",
    establishmentName: "Balima Minaret Suites",
    category: "Hotel",
    score: 9,
    snippet: "Beautifully renovated rooms. Staff were attentive and professional.",
    author: "Citizen #884",
    relativeTime: "3 hr ago",
    status: "verified",
  },
  {
    id: "rev-6",
    establishmentId: "lycee-descartes",
    establishmentName: "Lycée Descartes",
    category: "School",
    score: 9,
    snippet: "Excellent facility. Well-maintained labs and engaged teachers.",
    author: "Citizen #4401",
    relativeTime: "4 hr ago",
    status: "verified",
  },
  {
    id: "rev-7",
    establishmentId: "dar-naji",
    establishmentName: "Dar Naji Restaurant",
    category: "Restaurant",
    score: 8,
    snippet: "Authentic Moroccan cuisine. Portions generous and pricing fair.",
    author: "Citizen #772",
    relativeTime: "5 hr ago",
    status: "verified",
  },
  {
    id: "rev-8",
    establishmentId: "cozy-cafe",
    establishmentName: "Cozy Cafe",
    category: "Cafe",
    score: 5,
    snippet: "WiFi dropped twice during my visit. Coffee was decent though.",
    author: "Citizen #3310",
    relativeTime: "6 hr ago",
    status: "watch",
  },
];
