import type { Submission } from "./types";

export const analystSubmissions: Submission[] = [
  {
    id: "sub-108",
    establishmentId: "rabat-central-hospital",
    establishmentName: "Rabat Central Hospital",
    category: "Hospital",
    city: "Rabat",
    region: "Rabat-Salé-Kénitra",
    place: "hassan",
    submittedAt: "2026-06-30T09:42:00Z",
    reviewStatus: "new",
    answers: [
      { label: "issue", value: "wait time and triage delay" },
      { label: "impact", value: "urgent care blocked for 5 hours" },
      { label: "evidence", value: "2 photos, 1 short video" },
    ],
    note: "Citizen asked for follow-up after the night shift handoff.",
  },
  {
    id: "sub-107",
    establishmentId: "clinic-des-orangers",
    establishmentName: "Clinique des Orangers",
    category: "Clinic",
    city: "Rabat",
    region: "Rabat-Salé-Kénitra",
    place: "agdal",
    submittedAt: "2026-06-30T08:18:00Z",
    reviewStatus: "reviewed",
    answers: [
      { label: "issue", value: "front desk coverage gap" },
      { label: "impact", value: "patients waited without check-in" },
      { label: "evidence", value: "photo of empty desk" },
    ],
  },
  {
    id: "sub-106",
    establishmentId: "rabat-medina-market",
    establishmentName: "Bab El Had Medina Market",
    category: "Marketplace",
    city: "Rabat",
    region: "Rabat-Salé-Kénitra",
    place: "medina",
    submittedAt: "2026-06-30T07:54:00Z",
    reviewStatus: "grouped",
    answers: [
      { label: "issue", value: "sanitation and safety" },
      { label: "impact", value: "blocked exits near the fish stalls" },
      { label: "pattern", value: "matches two recent reports" },
    ],
    note: "Included in the morning market cluster.",
  },
  {
    id: "sub-105",
    establishmentId: "dar-naji",
    establishmentName: "Dar Naji Restaurant",
    category: "Restaurant",
    city: "Rabat",
    region: "Rabat-Salé-Kénitra",
    place: "ville nouvelle",
    submittedAt: "2026-06-30T06:36:00Z",
    reviewStatus: "exported",
    answers: [
      { label: "issue", value: "queue and service pace" },
      { label: "impact", value: "35 minute lunch wait" },
      { label: "routing", value: "sent to weekly export" },
    ],
  },
  {
    id: "sub-104",
    establishmentId: "cozy-cafe",
    establishmentName: "Cozy Cafe",
    category: "Cafe",
    city: "Rabat",
    region: "Rabat-Salé-Kénitra",
    place: "centre ville",
    submittedAt: "2026-06-30T05:10:00Z",
    reviewStatus: "new",
    answers: [
      { label: "issue", value: "wi-fi and table turnover" },
      { label: "impact", value: "work session interrupted twice" },
      { label: "evidence", value: "1 photo and 1 note" },
    ],
  },
  {
    id: "sub-103",
    establishmentId: "rabat-parlement",
    establishmentName: "Le Parlement du Maroc",
    category: "Public Office",
    city: "Rabat",
    region: "Rabat-Salé-Kénitra",
    place: "avenue mohammed v",
    submittedAt: "2026-06-29T18:44:00Z",
    reviewStatus: "reviewed",
    answers: [
      { label: "issue", value: "security checkpoint delay" },
      { label: "impact", value: "entry took 45 minutes" },
      { label: "routing", value: "flagged for access review" },
    ],
  },
  {
    id: "sub-102",
    establishmentId: "mcdonalds-rabat-ville",
    establishmentName: "McDonald's Rabat Ville",
    category: "Restaurant",
    city: "Rabat",
    region: "Rabat-Salé-Kénitra",
    place: "gare zone",
    submittedAt: "2026-06-29T15:12:00Z",
    reviewStatus: "grouped",
    answers: [
      { label: "issue", value: "order accuracy and table hygiene" },
      { label: "impact", value: "two wrong orders in one visit" },
      { label: "pattern", value: "paired with lunch crowd spike" },
    ],
  },
  {
    id: "sub-101",
    establishmentId: "hotel-balima",
    establishmentName: "Balima Minaret Suites",
    category: "Hotel",
    city: "Rabat",
    region: "Rabat-Salé-Kénitra",
    place: "avenue mohammed v",
    submittedAt: "2026-06-29T10:05:00Z",
    reviewStatus: "exported",
    answers: [
      { label: "issue", value: "positive service audit" },
      { label: "impact", value: "guest experience verified" },
      { label: "routing", value: "added to export bundle" },
    ],
    note: "This one is a clean reference submission for the export flow.",
  },
];
